version: "3"
services:
  app:
    build:
      context: ./docker
      args:
        - EAS_USER=${EAS_USER}
        - EAS_PASS=${EAS_PASS}
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: "development"
      JVM_OPTS: "-Xmx12g -Xms12g -XX:MaxPermSize=1024m"
    # ports:
    #   - 6767:6767
    command: eas build -p android --local