name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
        with:
          host: ${{ secrets.DO_IP }}
          user: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH }}
          
          first_ssh: |
            echo "hello"
